// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo8SdKF3o-WqeAjInMhKcdGYUDgwz95oY',
    appId: '1:885622060165:web:a819fc114b219d6cc7a5ec',
    messagingSenderId: '885622060165',
    projectId: 'ambw-uas',
    authDomain: 'ambw-uas.firebaseapp.com',
    storageBucket: 'ambw-uas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQCN6MEXRzfnURYN5PPAskTZK8xIHy86M',
    appId: '1:885622060165:android:5687c9b892fe25a1c7a5ec',
    messagingSenderId: '885622060165',
    projectId: 'ambw-uas',
    storageBucket: 'ambw-uas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1zWoqD3gx00vsELAlB9uzIrBEvQI1-ko',
    appId: '1:885622060165:ios:85b692a27bb43028c7a5ec',
    messagingSenderId: '885622060165',
    projectId: 'ambw-uas',
    storageBucket: 'ambw-uas.appspot.com',
    iosClientId: '885622060165-821nper1np7sf2lvobl8livg3fhbe143.apps.googleusercontent.com',
    iosBundleId: 'com.example.c14190091Uas',
  );
}
